# TODO(hector): NEEDS WORK - postgres starts too damn slow
#  https://hub.docker.com/r/jbergknoff/postgresql-client/dockerfile

version: "3"
services:
  db:
    image: postgres:12.3
    ports:
        - "5432:5432"
    networks:
      - bot_worker 
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rotom_b
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
  rotomb:
    build: .
    restart: on-failure:5
    networks: 
      - bot_worker
    volumes:
      - ./config.yaml:/app/config.yaml
    depends_on:
      - db

networks:
  bot_worker:

volumes:
  db-data:
